#include "hal_data.h"
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include "tmp512.h"

#define REGISTER_ADDRESS 0x08

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
void TMP512_Initialize(i2c_master_ctrl_t * const p_api_ctrl, i2c_master_cfg_t const * const p_cfg);
void TMP512_Read(i2c_master_ctrl_t *const p_api_ctrl, uint8_t reg, uint8_t *const  p_dest, uint32_t const  bytes);

FSP_CPP_FOOTER
//volatile bool rx_done = false;
volatile bool tx_done = false;

/*void IIC_Receive(i2c_master_callback_args_t *p_args)
{
    if(p_args->event ==  I2C_MASTER_EVENT_RX_COMPLETE){
        rx_done = true;
        p_args->event = I2C_MASTER_EVENT_NONE;
    }
}*/
void UART_Interrupt(uart_callback_args_t *p_args)
{
    if(p_args->event ==  UART_EVENT_TX_COMPLETE){
            tx_done = true;
            p_args->event = UART_EVENT_NONE;
        }
}

/*void TMP512_Initialize(i2c_master_ctrl_t * const p_api_ctrl, i2c_master_cfg_t const * const p_cfg)
{
    fsp_err_t err = R_IIC_MASTER_Open(p_api_ctrl, p_cfg);
    if(err == FSP_SUCCESS){
        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_07, BSP_IO_LEVEL_HIGH);
    }
}

void TMP512_Read(i2c_master_ctrl_t *const p_api_ctrl, uint8_t reg, uint8_t *const  p_dest, uint32_t const  bytes)
{
    fsp_err_t err = R_IIC_MASTER_Write(p_api_ctrl, &reg, 1, true);
    if(err == FSP_SUCCESS){
        rx_done = false;
        fsp_err_t err2 = R_IIC_MASTER_Read(p_api_ctrl, p_dest, bytes, false);
        if(err2 == FSP_SUCCESS){
            R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_06, BSP_IO_LEVEL_HIGH);
            while(!rx_done);
        }
        }
}*/


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    uint8_t data[2];
    double real_temperature = 0;
    uint16_t raw_data;
    bool is_negative = false;
    char buff[64];

    TMP512_Initialize(&g_i2c_master0_ctrl, &g_i2c_master0_cfg);
    R_SCI_UART_Open(&g_uart0_ctrl, &g_uart0_cfg);
    while(1){
        TMP512_Read(&g_i2c_master0_ctrl, REGISTER_ADDRESS, data, 2);

        raw_data = (data[0] << 8) | data[1];
        is_negative = (raw_data >> 12) & 1;
        if(!is_negative){
            real_temperature = raw_data *(0.0625);
        }else if(is_negative){
            raw_data = raw_data - 1;
            raw_data = ~(raw_data);
            real_temperature = -(raw_data * (0.0625));
        }

        sprintf(buff, "temperature : %f\n", real_temperature);
        tx_done = false;
        R_SCI_UART_Write(&g_uart0_ctrl, (uint8_t *)buff, strlen(buff));
        while(!tx_done);
        //R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_SECONDS);
    }


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
